<a href="https://colab.research.google.com/github/kauefs/ML/blob/%40/notebooks/AnomalyDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>

<font color=F0F0F0 size=8px font-family=Georgia>
<strong><ins>ƊⱭȾɅViƧi&#x1F9FF;Ƞ</ins>&trade;</strong></font>

[![ƊⱭȾɅViƧi🧿Ƞ](https://img.shields.io/badge/ƊⱭȾɅViƧi&#x1F9FF;Ƞ&trade;-0065FF?style=plastic)](https://datavision.one/)

[![GitHub     ](https://img.shields.io/badge/-000000?logo=github&logoColor=FFFFFF)](https://github.com/kauefs/)
[![Medium     ](https://img.shields.io/badge/-000000?logo=medium&logoColor=FFFFFF)](https://medium.com/@kauefs)
[![LinkedIn   ](https://img.shields.io/badge/-2867B2?logo=linkedin&logoColor=FFFFFF)](https://www.linkedin.com/in/kauefs/)
[![Python     ](https://img.shields.io/badge/3-646464?logo=python&logoColor=FFDE57&labelColor=4584B6)](https://www.python.org/)

[![License]( https://img.shields.io/badge/Apache--2.0-D22128?style=flat&logo=apache&logoColor=CB2138&label=License&labelColor=6D6E71&color=D22128)](https://www.apache.org/licenses/LICENSE-2.0)

![2024.12.20  ](https://img.shields.io/badge/2024.12.20-000000)

In [1]:
!date

Sat Dec 21 05:33:53 AM UTC 2024

---
<center>
    <a heref=https://pycaret.readthedocs.io/en/latest/index.html><img src=https://pycaret.org/wp-content/uploads/2020/03/Divi93_43.png></a>
</center>

# Anomaly Detection

In [2]:
# @title Libraries
%pip install -U -q pip pandas matplotlib mlflow umap-learn pycaret
import      numpy            as   np
import     pandas            as   pd
import matplotlib.pyplot     as   plt
import    seaborn            as   sns
import                            sys
import     mlflow
import       umap
from       mlflow          import    *
from         umap          import    *
from      pycaret.datasets import get_data
from      pycaret.anomaly  import setup, create_model, assign_model, plot_model, predict_model, save_model, load_model, evaluate_model, AnomalyExperiment
from      pycaret.anomaly  import AnomalyExperiment, models, get_config, set_config, evaluate_model, save_experiment, load_experiment
# Configurations:
print('System Ready: Python –',   sys.version)
%matplotlib inline
%config     InlineBackend.figure_format='svg'
# %config     InlineBackend.print_figure_kwargs={'bbox_inches':None}
# %precision 2
pd.options.plotting.matplotlib.register_converters=True
pd.set_option('display.max.columns',               None)
plt.rcParams[      'font.family']      =                                        'sans-serif'
sns.set_theme(context='notebook', style='whitegrid', palette='colorblind', font='sans-serif', font_scale=1.15, color_codes=True, rc={'grid.color':'1','grid.linestyle':':'})

System Ready: Python – 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]

In [3]:
# @title Data
# LoadData:
data=get_data('anomaly')

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10
0,0.263995,0.764929,0.138424,0.935242,0.605867,0.518790,0.912225,0.608234,0.723782,0.733591
1,0.546092,0.653975,0.065575,0.227772,0.845269,0.837066,0.272379,0.331679,0.429297,0.367422
2,0.336714,0.538842,0.192801,0.553563,0.074515,0.332993,0.365792,0.861309,0.899017,0.088600
3,0.092108,0.995017,0.014465,0.176371,0.241530,0.514724,0.562208,0.158963,0.073715,0.208463
4,0.325261,0.805968,0.957033,0.331665,0.307923,0.355315,0.501899,0.558449,0.885169,0.182754

In [4]:
# Data Info:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    1000 non-null   float64
 1   Col2    1000 non-null   float64
 2   Col3    1000 non-null   float64
 3   Col4    1000 non-null   float64
 4   Col5    1000 non-null   float64
 5   Col6    1000 non-null   float64
 6   Col7    1000 non-null   float64
 7   Col8    1000 non-null   float64
 8   Col9    1000 non-null   float64
 9   Col10   1000 non-null   float64
dtypes: float64(10)
memory usage: 78.2 KB

In [5]:
# @title Train & Test Split
test  =data.sample(frac=.10)
train =data.drop(test.index)
test.reset_index( inplace=True, drop=True)
train.reset_index(inplace=True, drop=True)
print('\t',train.shape,
    '\n\t', test.shape)

	 (900, 10)
	 (100, 10)

In [6]:
# @title SetUp
# SetUp Help:
help(setup)

Help on function setup in module pycaret.anomaly.functional:

setup(data: Union[dict, list, tuple, numpy.ndarray, scipy.sparse._matrix.spmatrix, pandas.core.frame.DataFrame, NoneType] = None, data_func: Optional[Callable[[], Union[dict, list, tuple, numpy.ndarray, scipy.sparse._matrix.spmatrix, pandas.core.frame.DataFrame]]] = None, index: Union[bool, int, str, list, tuple, numpy.ndarray, pandas.core.series.Series] = True, ordinal_features: Optional[Dict[str, list]] = None, numeric_features: Optional[List[str]] = None, categorical_features: Optional[List[str]] = None, date_features: Optional[List[str]] = None, text_features: Optional[List[str]] = None, ignore_features: Optional[List[str]] = None, keep_features: Optional[List[str]] = None, preprocess: bool = True, create_date_columns: List[str] = ['day', 'month', 'year'], imputation_type: Optional[str] = 'simple', numeric_imputation: str = 'mean', categorical_imputation: str = 'mode', text_features_method: str = 'tf-idf', max_encoding_ohe: int = -1, encoding_method: Optional[Any] = None, rare_to_value: Optional[float] = None, rare_value: str = 'rare', polynomial_features: bool = False, polynomial_degree: int = 2, low_variance_threshold: Optional[float] = None, group_features: Optional[dict] = None, drop_groups: bool = False, remove_multicollinearity: bool = False, multicollinearity_threshold: float = 0.9, bin_numeric_features: Optional[List[str]] = None, remove_outliers: bool = False, outliers_method: str = 'iforest', outliers_threshold: float = 0.05, transformation: bool = False, transformation_method: str = 'yeo-johnson', normalize: bool = False, normalize_method: str = 'zscore', pca: bool = False, pca_method: str = 'linear', pca_components: Union[int, float, str, NoneType] = None, custom_pipeline: Optional[Any] = None, custom_pipeline_position: int = -1, n_jobs: Optional[int] = -1, use_gpu: bool = False, html: bool = True, session_id: Optional[int] = None, system_log: Union[bool, str, logging.Logger] = True, log_experiment: Union[bool, str, pycaret.loggers.base_logger.BaseLogger, List[Union[str, pycaret.loggers.base_logger.BaseLogger]]] = False, experiment_name: Optional[str] = None, experiment_custom_tags: Optional[Dict[str, Any]] = None, log_plots: Union[bool, list] = False, log_profile: bool = False, log_data: bool = False, verbose: bool = True, memory: Union[bool, str, joblib.memory.Memory] = True, profile: bool = False, profile_kwargs: Optional[Dict[str, Any]] = None)
    This function initializes the training environment and creates the transformation
    pipeline. Setup function must be called before executing any other function. It
    takes one mandatory parameter: ``data``. All the other parameters are optional.


    Example
    -------
    >>> from pycaret.datasets import get_data
    >>> anomaly = get_data('anomaly')
    >>> from pycaret.anomaly import *
    >>> exp_name = setup(data = anomaly)


    data: dataframe-like
        Data set with shape (n_samples, n_features), where n_samples is the
        number of samples and n_features is the number of features. If data
        is not a pandas dataframe, it's converted to one using default column
        names.


    data_func: Callable[[], DATAFRAME_LIKE] = None
        The function that generate ``data`` (the dataframe-like input). This
        is useful when the dataset is large, and you need parallel operations
        such as ``compare_models``. It can avoid broadcasting large dataset
        from driver to workers. Notice one and only one of ``data`` and
        ``data_func`` must be set.


    index: bool, int, str or sequence, default = True
        Handle indices in the `data` dataframe.
            - If False: Reset to RangeIndex.
            - If True: Keep the provided index.
            - If int: Position of the column to use as index.
            - If str: Name of the column to use as index.
            - If sequence: Array with shape=(n_samples,) to use as index.


    ordinal_features: dict, default = None
        Categorical features to be encoded ordinally. For example, a categorical
        feature with 'low', 'medium', 'high' values where low < medium < high can
        be passed as ordinal_features = {'column_name' : ['low', 'medium', 'high']}.


    numeric_features: list of str, default = None
        If the inferred data types are not correct, the numeric_features param can
        be used to define the data types. It takes a list of strings with column
        names that are numeric.


    categorical_features: list of str, default = None
        If the inferred data types are not correct, the categorical_features param
        can be used to define the data types. It takes a list of strings with column
        names that are categorical.


    date_features: list of str, default = None
        If the inferred data types are not correct, the date_features param can be
        used to overwrite the data types. It takes a list of strings with column
        names that are DateTime.


    text_features: list of str, default = None
        Column names that contain a text corpus. If None, no text features are
        selected.


    ignore_features: list of str, default = None
        ignore_features param can be used to ignore features during preprocessing
        and model training. It takes a list of strings with column names that are
        to be ignored.


    keep_features: list of str, default = None
        keep_features param can be used to always keep specific features during
        preprocessing, i.e. these features are never dropped by any kind of
        feature selection. It takes a list of strings with column names that are
        to be kept.


    preprocess: bool, default = True
        When set to False, no transformations are applied except for train_test_split
        and custom transformations passed in ``custom_pipeline`` param. Data must be
        ready for modeling (no missing values, no dates, categorical data encoding),
        when preprocess is set to False.


    create_date_columns: list of str, default = ["day", "month", "year"]
        Columns to create from the date features. Note that created features
        with zero variance (e.g. the feature hour in a column that only contains
        dates) are ignored. Allowed values are datetime attributes from
        `pandas.Series.dt`. The datetime format of the feature is inferred
        automatically from the first non NaN value.


    imputation_type: str or None, default = 'simple'
        The type of imputation to use. Unsupervised learning only supports
        'imputation_type=simple'. If None, no imputation of missing values
        is performed.


    numeric_imputation: str, default = 'mean'
        Missing values in numeric features are imputed with 'mean' value of the feature
        in the training dataset. The other available option is 'median' or 'zero'.


    categorical_imputation: str, default = 'constant'
        Missing values in categorical features are imputed with a constant 'not_available'
        value. The other available option is 'mode'.


    text_features_method: str, default = "tf-idf"
        Method with which to embed the text features in the dataset. Choose
        between "bow" (Bag of Words - CountVectorizer) or "tf-idf" (TfidfVectorizer).
        Be aware that the sparse matrix output of the transformer is converted
        internally to its full array. This can cause memory issues for large
        text embeddings.


    max_encoding_ohe: int, default = -1
        Categorical columns with `max_encoding_ohe` or less unique values are
        encoded using OneHotEncoding. If more, the `encoding_method` estimator
        is used. Note that columns with exactly two classes are always encoded
        ordinally. Set to below 0 to always use OneHotEncoding.


    encoding_method: category-encoders estimator, default = None
        A `category-encoders` estimator to encode the categorical columns
        with more than `max_encoding_ohe` unique values. If None,
        `category_encoders.basen.BaseN` is used.


    rare_to_value: float or None, default=None
        Minimum fraction of category occurrences in a categorical column.
        If a category is less frequent than `rare_to_value * len(X)`, it is
        replaced with the string `other`. Use this parameter to group rare
        categories before encoding the column. If None, ignores this step.


    polynomial_features: bool, default = False
        When set to True, new features are derived using existing numeric features.


    polynomial_degree: int, default = 2
        Degree of polynomial features. For example, if an input sample is two dimensional
        and of the form [a, b], the polynomial features with degree = 2 are:
        [1, a, b, a^2, ab, b^2]. Ignored when ``polynomial_features`` is not True.


    low_variance_threshold: float or None, default = None
        Remove features with a training-set variance lower than the provided
        threshold. If 0, keep all features with non-zero variance, i.e. remove
        the features that have the same value in all samples. If None, skip
        this transformation step.


    group_features: dict or None, default = None
        When the dataset contains features with related characteristics,
        add new fetaures with the following statistical properties of that
        group: min, max, mean, std, median and mode. The parameter takes a
        dict with the group name as key and a list of feature names
        belonging to that group as value.


    drop_groups: bool, default=False
        Whether to drop the original features in the group. Ignored when
        ``group_features`` is None.


    remove_multicollinearity: bool, default = False
        When set to True, features with the inter-correlations higher than
        the defined threshold are removed. For each group, it removes all
        except the first feature.


    multicollinearity_threshold: float, default = 0.9
        Minimum absolute Pearson correlation to identify correlated
        features. The default value removes equal columns. Ignored when
        ``remove_multicollinearity`` is not True.


    bin_numeric_features: list of str, default = None
        To convert numeric features into categorical, bin_numeric_features parameter can
        be used. It takes a list of strings with column names to be discretized. It does
        so by using 'sturges' rule to determine the number of clusters and then apply
        KMeans algorithm. Original values of the feature are then replaced by the
        cluster label.


    remove_outliers: bool, default = False
        When set to True, outliers from the training data are removed using an
        Isolation Forest.


    outliers_method: str, default = "iforest"
        Method with which to remove outliers. Possible values are:
            - 'iforest': Uses sklearn's IsolationForest.
            - 'ee': Uses sklearn's EllipticEnvelope.
            - 'lof': Uses sklearn's LocalOutlierFactor.


    outliers_threshold: float, default = 0.05
        The percentage outliers to be removed from the dataset. Ignored
        when ``remove_outliers=False``.


    transformation: bool, default = False
        When set to True, it applies the power transform to make data more Gaussian-like.
        Type of transformation is defined by the ``transformation_method`` parameter.


    transformation_method: str, default = 'yeo-johnson'
        Defines the method for transformation. By default, the transformation method is
        set to 'yeo-johnson'. The other available option for transformation is 'quantile'.
        Ignored when ``transformation`` is not True.


    normalize: bool, default = False
        When set to True, it transforms the features by scaling them to a given
        range. Type of scaling is defined by the ``normalize_method`` parameter.


    normalize_method: str, default = 'zscore'
        Defines the method for scaling. By default, normalize method is set to 'zscore'
        The standard zscore is calculated as z = (x - u) / s. Ignored when ``normalize``
        is not True. The other options are:

        - minmax: scales and translates each feature individually such that it is in
          the range of 0 - 1.
        - maxabs: scales and translates each feature individually such that the
          maximal absolute value of each feature will be 1.0. It does not
          shift/center the data, and thus does not destroy any sparsity.
        - robust: scales and translates each feature according to the Interquartile
          range. When the dataset contains outliers, robust scaler often gives
          better results.


    pca: bool, default = False
        When set to True, dimensionality reduction is applied to project the data into
        a lower dimensional space using the method defined in ``pca_method`` parameter.


    pca_method: str, default = 'linear'
        Method with which to apply PCA. Possible values are:
            - 'linear': Uses Singular Value  Decomposition.
            - 'kernel': Dimensionality reduction through the use of RBF kernel.
            - 'incremental': Similar to 'linear', but more efficient for large datasets.


    pca_components: int, float, str or None, default = None
        Number of components to keep. This parameter is ignored when `pca=False`.
            - If None: All components are kept.
            - If int: Absolute number of components.
            - If float: Such an amount that the variance that needs to be explained
                        is greater than the percentage specified by `n_components`.
                        Value should lie between 0 and 1 (ony for pca_method='linear').
            - If "mle": Minka’s MLE is used to guess the dimension (ony for pca_method='linear').


    custom_pipeline: list of (str, transformer), dict or Pipeline, default = None
        Addidiotnal custom transformers. If passed, they are applied to the
        pipeline last, after all the build-in transformers.


    custom_pipeline_position: int, default = -1
        Position of the custom pipeline in the overal preprocessing pipeline.
        The default value adds the custom pipeline last.


    n_jobs: int, default = -1
        The number of jobs to run in parallel (for functions that supports parallel
        processing) -1 means using all processors. To run all functions on single
        processor set n_jobs to None.


    use_gpu: bool or str, default = False
        When set to True, it will use GPU for training with algorithms that support it,
        and fall back to CPU if they are unavailable. When set to 'force', it will only
        use GPU-enabled algorithms and raise exceptions when they are unavailable. When
        False, all algorithms are trained using CPU only.

        GPU enabled algorithms:

        - None at this moment.


    html: bool, default = True
        When set to False, prevents runtime display of monitor. This must be set to False
        when the environment does not support IPython. For example, command line terminal,
        Databricks Notebook, Spyder and other similar IDEs.


    session_id: int, default = None
        Controls the randomness of experiment. It is equivalent to 'random_state' in
        scikit-learn. When None, a pseudo random number is generated. This can be used
        for later reproducibility of the entire experiment.


    system_log: bool or str or logging.Logger, default = True
        Whether to save the system logging file (as logs.log). If the input
        is a string, use that as the path to the logging file. If the input
        already is a logger object, use that one instead.


    log_experiment: bool, default = False
        A (list of) PyCaret ``BaseLogger`` or str (one of 'mlflow', 'wandb', 'comet_ml')
        corresponding to a logger to determine which experiment loggers to use.
        Setting to True will use just MLFlow.


    experiment_name: str, default = None
        Name of the experiment for logging. Ignored when ``log_experiment`` is False.


    experiment_custom_tags: dict or None, default = None
        Dictionary of tag_name: String -> value: (String, but will be string-ified
        if not) passed to the mlflow.set_tags to add new custom tags for the experiment.


    log_plots: bool or list, default = False
        When set to True, certain plots are logged automatically in the ``MLFlow`` server.
        To change the type of plots to be logged, pass a list containing plot IDs. Refer
        to documentation of ``plot_model``. Ignored when ``log_experiment`` is False.


    log_profile: bool, default = False
        When set to True, data profile is logged on the ``MLflow`` server as a html file.
        Ignored when ``log_experiment`` is False.


    log_data: bool, default = False
        When set to True, dataset is logged on the ``MLflow`` server as a csv file.
        Ignored when ``log_experiment`` is False.


    verbose: bool, default = True
        When set to False, Information grid is not printed.


    memory: str, bool or Memory, default=True
        Used to cache the fitted transformers of the pipeline.
            If False: No caching is performed.
            If True: A default temp directory is used.
            If str: Path to the caching directory.


    profile: bool, default = False
        When set to True, an interactive EDA report is displayed.


    profile_kwargs: dict, default = {} (empty dict)
        Dictionary of arguments passed to the ProfileReport method used
        to create the EDA report. Ignored if ``profile`` is False.


    Returns:
        Global variables that can be changed using the ``set_config`` function.

In [7]:
# SetUp:
anomaly=setup(data=train, normalize=True, session_id=0, experiment_name='anomaly')

In [8]:
# Available Config:
get_config()

{'USI',
 'X',
 'X_train',
 'X_train_transformed',
 'X_transformed',
 '_available_plots',
 '_ml_usecase',
 'data',
 'dataset',
 'dataset_transformed',
 'exp_id',
 'exp_name_log',
 'gpu_n_jobs_param',
 'gpu_param',
 'html_param',
 'idx',
 'is_multiclass',
 'log_plots_param',
 'logging_param',
 'memory',
 'n_jobs_param',
 'pipeline',
 'seed',
 'train',
 'train_transformed',
 'variable_and_property_keys',
 'variables'}

In [9]:
# Accessing    Seed:
print('Current Seed: {}'.format(get_config('seed')))
# Changing     Seed:
# set_config(   'seed'    ,                   123    )
# print('New     Seed: {}'.format(get_config('seed')))

Current Seed: 0

In [10]:
# @title Create Model
# Verifying Models:
models()

,Name,Reference
ID,,
abod,Angle-base Outlier Detection,pyod.models.abod.ABOD
cluster,Clustering-Based Local Outlier,pycaret.internal.patches.pyod.CBLOFForceToDouble
cof,Connectivity-Based Local Outlier,pyod.models.cof.COF
iforest,Isolation Forest,pyod.models.iforest.IForest
histogram,Histogram-based Outlier Detection,pyod.models.hbos.HBOS
knn,K-Nearest Neighbors Detector,pyod.models.knn.KNN
lof,Local Outlier Factor,pyod.models.lof.LOF
svm,One-class SVM detector,pyod.models.ocsvm.OCSVM
pca,Principal Component Analysis,pyod.models.pca.PCA
mcd,Minimum Covariance Determinant,pyod.models.mcd.MCD
sod,Subspace Outlier Detection,pyod.models.sod.SOD
sos,Stochastic Outlier Selection,pyod.models.sos.SOS

In [11]:
# Create Model Help:
help(create_model)

Help on function create_model in module pycaret.anomaly.functional:

create_model(model: Union[str, Any], fraction: float = 0.05, verbose: bool = True, fit_kwargs: Optional[dict] = None, experiment_custom_tags: Optional[Dict[str, Any]] = None, **kwargs)
    This function trains a given model from the model library. All available
    models can be accessed using the ``models`` function.


    Example
    -------
    >>> from pycaret.datasets import get_data
    >>> anomaly = get_data('anomaly')
    >>> from pycaret.anomaly import *
    >>> exp_name = setup(data = anomaly)
    >>> knn = create_model('knn')


    model: str or scikit-learn compatible object
        ID of an model available in the model library or pass an untrained
        model object consistent with scikit-learn API. Estimators available
        in the model library (ID - Name):

        * 'abod' - Angle-base Outlier Detection
        * 'cluster' - Clustering-Based Local Outlier
        * 'cof' - Connectivity-Based Outlier Factor
        * 'histogram' - Histogram-based Outlier Detection
        * 'iforest' - Isolation Forest
        * 'knn' - k-Nearest Neighbors Detector
        * 'lof' - Local Outlier Factor
        * 'svm' - One-class SVM detector
        * 'pca' - Principal Component Analysis
        * 'mcd' - Minimum Covariance Determinant
        * 'sod' - Subspace Outlier Detection
        * 'sos' - Stochastic Outlier Selection


    fraction: float, default = 0.05
        The amount of contamination of the data set, i.e. the proportion of
        outliers in the data set. Used when fitting to define the threshold on
        the decision function.


    verbose: bool, default = True
        Status update is not printed when verbose is set to False.


    experiment_custom_tags: dict, default = None
        Dictionary of tag_name: String -> value: (String, but will be string-ified
        if not) passed to the mlflow.set_tags to add new custom tags for the experiment.


    fit_kwargs: dict, default = {} (empty dict)
        Dictionary of arguments passed to the fit method of the model.


    **kwargs:
        Additional keyword arguments to pass to the estimator.


    Returns:
        Trained Model

In [12]:
# Create Model:
pca=create_model('pca')
# Verifying ParaMeters:
pca

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

PCA(contamination=0.05, copy=True, iterated_power='auto', n_components=None,
  n_selected_components=None, random_state=0, standardization=True,
  svd_solver='auto', tol=0.0, weighted=True, whiten=False)

In [13]:
# Type:
type(pca)

pyod.models.pca.PCA

In [14]:
# @title Assign Model
# Assign Model Help
help(assign_model)

Help on function assign_model in module pycaret.anomaly.functional:

assign_model(model, transformation: bool = False, score: bool = True, verbose: bool = True) -> pandas.core.frame.DataFrame
    This function assigns anomaly labels to the dataset for a given model.
    (1 = outlier, 0 = inlier).


    Example
    -------
    >>> from pycaret.datasets import get_data
    >>> anomaly = get_data('anomaly')
    >>> from pycaret.anomaly import *
    >>> exp_name = setup(data = anomaly)
    >>> knn = create_model('knn')
    >>> knn_df = assign_model(knn)


    model: scikit-learn compatible object
        Trained model object


    transformation: bool, default = False
        Whether to apply anomaly labels on the transformed dataset.


    score: bool, default = True
        Whether to show outlier score or not.


    verbose: bool, default = True
        Status update is not printed when verbose is set to False.


    Returns:
        pandas.DataFrame

In [15]:
# Model Instance
# Model Designation (Assign) & Recording Results to a Variable:
results=assign_model(pca)
# Label/Anomaly: 0 = No Anomaly & 1 = With Anomaly
# Anomaly Score:        Anomaly Score
results#.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
0,0.263995,0.764929,0.138424,0.935242,0.605867,0.518790,0.912225,0.608234,0.723782,0.733591,0,805.943919
1,0.546092,0.653975,0.065575,0.227772,0.845269,0.837066,0.272379,0.331679,0.429297,0.367422,0,683.175699
2,0.336714,0.538842,0.192801,0.553563,0.074515,0.332993,0.365792,0.861309,0.899017,0.088600,0,902.459358
3,0.325261,0.805968,0.957033,0.331665,0.307923,0.355315,0.501899,0.558449,0.885169,0.182754,0,799.043911
4,0.212465,0.780305,0.458444,0.634509,0.373030,0.465651,0.413997,0.013080,0.570250,0.736672,0,698.881862
...,...,...,...,...,...,...,...,...,...,...,...,...
895,0.305055,0.656837,0.331665,0.822525,0.907127,0.882276,0.855732,0.584786,0.808640,0.242762,0,773.302071
896,0.812627,0.864258,0.616604,0.167966,0.811223,0.938071,0.418462,0.472306,0.348347,0.671129,0,698.729545
897,0.250967,0.138627,0.919703,0.461234,0.886555,0.869888,0.800908,0.530324,0.779433,0.234952,0,817.069359
898,0.502436,0.936820,0.580062,0.540773,0.151995,0.059452,0.225220,0.242755,0.279385,0.538755,0,753.534388
899,0.457991,0.017755,0.714113,0.125992,0.063316,0.154739,0.922974,0.692299,0.816777,0.307592,1,937.032461

In [16]:
# Verifying Results for Label == 1:
results[results['Anomaly'] == 1]

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
6,0.869237,0.277979,0.423076,0.112472,0.183727,0.034960,0.111114,0.249330,0.550683,0.049843,1,966.384669
10,0.796623,0.230543,0.993018,0.077075,0.094068,0.718628,0.977611,0.333386,0.634843,0.028729,1,1017.055388
19,0.162825,0.674069,0.705447,0.774799,0.894267,0.443057,0.399779,0.009136,0.941851,0.982711,1,988.439964
22,0.057884,0.227162,0.022494,0.167069,0.631315,0.610103,0.277753,0.728503,0.716414,0.973370,1,975.459812
27,0.834861,0.973891,0.808398,0.222828,0.018934,0.708188,0.986392,0.545479,0.235898,0.844788,1,957.999811
28,0.669766,0.694779,0.191048,0.080716,0.441480,0.115675,0.054466,0.949300,0.318667,0.410017,1,942.131001
32,0.249776,0.276445,0.905772,0.843307,0.622943,0.757426,0.656207,0.887785,0.040510,0.808190,1,935.870685
40,0.178173,0.304310,0.028749,0.800844,0.161153,0.874650,0.984053,0.205747,0.029727,0.842088,1,1034.894163
49,0.273081,0.097663,0.491502,0.065955,0.087729,0.727527,0.004372,0.903040,0.254568,0.402991,1,950.802912
55,0.981709,0.253236,0.695971,0.918359,0.108317,0.656997,0.806218,0.924069,0.916568,0.406505,1,978.091164
59,0.837803,0.793079,0.003605,0.165423,0.170273,0.374682,0.514763,0.185381,0.079298,0.954650,1,1028.376076
118,0.184401,0.182524,0.155665,0.824050,0.803282,0.856811,0.082615,0.699480,0.124231,0.956393,1,1008.519238
124,0.598231,0.934790,0.603668,0.426760,0.181692,0.120848,0.952934,0.543829,0.953942,0.070000,1,971.890295
175,0.271132,0.099214,0.326103,0.925654,0.910054,0.897757,0.965498,0.596357,0.933402,0.126133,1,1009.627813
203,0.744041,0.133710,0.372605,0.818695,0.092383,0.031271,0.271297,0.782089,0.192954,0.910245,1,977.133052
212,0.091210,0.665928,0.291810,0.945471,0.085347,0.058494,0.819760,0.492585,0.827875,0.161014,1,968.007828
225,0.245236,0.918462,0.157465,0.756813,0.821578,0.555554,0.856243,0.427849,0.915980,0.029184,1,984.521021
280,0.204932,0.818071,0.270969,0.871795,0.132823,0.146509,0.879894,0.548798,0.862308,0.164798,1,941.837556
328,0.377060,0.668582,0.514935,0.228115,0.137893,0.143976,0.493819,1.000000,0.241229,0.921220,1,940.230486
352,0.879902,0.745380,0.059787,0.417388,0.801933,0.502840,0.942938,0.523867,0.955438,0.054962,1,1001.402989
368,0.053484,0.620906,0.486275,0.887948,0.110199,0.040005,0.091565,0.248584,0.113925,0.707795,1,956.416140
440,0.280882,0.906832,0.217241,0.787382,0.822524,0.936131,0.911027,0.556837,0.894460,0.138173,1,947.508741
466,0.376381,0.069720,0.757846,0.125520,0.810560,0.653261,0.411480,0.920367,0.223094,0.917702,1,953.443938
474,0.902588,0.751362,0.002002,0.377471,0.052491,0.122550,0.854821,0.757885,0.689827,0.478754,1,936.801296
544,0.685463,0.881432,0.224920,0.859908,0.049718,0.073216,0.440065,0.926105,0.235349,0.907032,1,1040.636104
610,0.372957,0.050982,0.193545,0.768115,0.113805,0.129580,0.116132,0.308542,0.102836,0.759541,1,942.729660
630,0.539521,0.006844,0.379683,0.915896,0.708540,0.606755,0.504256,0.941473,0.019866,0.092027,1,1042.213727
637,0.052790,0.566393,0.285096,0.795340,0.523659,0.964553,0.789691,0.944700,0.062553,0.179371,1,1009.750242
642,0.495705,0.063449,0.054014,0.832054,0.790832,0.229366,0.425390,0.050938,0.725988,0.942197,1,1000.847188
646,0.159682,0.825127,0.716445,0.069445,0.032148,0.654702,0.028203,0.886761,0.165482,0.116204,1,1072.981481
647,0.318134,0.984550,0.858386,0.872008,0.950152,0.298551,0.275030,0.207604,0.855490,0.191021,1,970.578009
649,0.064359,0.129525,0.183766,0.860040,0.254505,0.440920,0.089274,0.941902,0.904978,0.215016,1,1071.967825
651,0.776252,0.416737,0.155131,0.556724,0.937436,0.091686,0.689603,0.064191,0.119276,0.985357,1,1017.156219
653,0.625105,0.873683,0.184258,0.907081,0.086882,0.856332,0.040426,0.755437,0.161329,0.748238,1,954.420757
670,0.281576,0.400546,0.310430,0.922162,0.125541,0.042865,0.406634,0.895068,0.227634,0.906307,1,973.382574
695,0.010984,0.511932,0.558768,0.064734,0.142256,0.051503,0.876103,0.526885,0.872629,0.139632,1,995.633423
706,0.708035,0.422559,0.359610,0.327955,0.929780,0.933195,0.987690,0.563922,0.982274,0.055364,1,948.950184
710,0.462532,0.059761,0.854265,0.132167,0.888607,0.470744,0.886331,0.526414,0.885308,0.126663,1,943.232940
741,0.297878,0.900762,0.314656,0.820577,0.229522,0.134788,0.875230,0.484171,0.900622,0.082721,1,961.500441
755,0.170195,0.785182,0.510915,0.119100,0.100409,0.142200,0.920733,0.586520,0.886002,0.166752,1,952.924959
804,0.920740,0.378674,0.093806,0.420244,0.150863,0.070104,0.905117,0.600903,0.857353,0.205095,1,950.576074
850,0.305762,0.129116,0.274433,0.846154,0.764555,0.866288,0.385277,0.899108,0.216213,0.918798,1,939.680864
852,0.063633,0.364433,0.166144,0.779080,0.015661,0.135076,0.106929,0.210755,0.158215,0.637939,1,948.028959
876,0.063201,0.400726,0.903851,0.406240,0.225658,0.106074,0.903802,0.548935,0.891103,0.136162,1,956.952265
899,0.457991,0.017755,0.714113,0.125992,0.063316,0.154739,0.922974,0.692299,0.816777,0.307592,1,937.032461

In [17]:
# @title Plot Model
# Checking DocString for Available Plots:
help(plot_model)

Help on function plot_model in module pycaret.anomaly.functional:

plot_model(model, plot: str = 'tsne', feature: Optional[str] = None, label: bool = False, scale: float = 1, save: bool = False, display_format: Optional[str] = None) -> Optional[str]
    This function analyzes the performance of a trained model.


    Example
    -------
    >>> from pycaret.datasets import get_data
    >>> anomaly = get_data('anomaly')
    >>> from pycaret.anomaly import *
    >>> exp_name = setup(data = anomaly)
    >>> knn = create_model('knn')
    >>> plot_model(knn, plot = 'tsne')


    model: scikit-learn compatible object
        Trained Model Object


    plot: str, default = 'tsne'
        List of available plots (ID - Name):

        * 'tsne' - t-SNE (3d) Dimension Plot
        * 'umap' - UMAP Dimensionality Plot


    feature: str, default = None
        Feature to be used as a hoverover tooltip and/or label when the ``label``
        param is set to True. When feature is None, first column of the dataset
        is used.


    label: bool, default = False
        Name of column to be used as data labels.


    scale: float, default = 1
        The resolution scale of the figure.


    save: bool, default = False
        When set to True, plot is saved in the current working directory.


    display_format: str, default = None
        To display plots in Streamlit (https://www.streamlit.io/), set this to 'streamlit'.
        Currently, not all plots are supported.


    Returns:
        Path to saved file, if any.

In [18]:
# Visualyzing/Analysing Results – tSNE:
plot_model(pca         ,    plot='tsne')

In [19]:
# Visualyzing/Analysing Results – UMAP:
plot_model(pca         ,    plot='umap')

In [20]:
# # Test Predictions:
predictions=predict_model(pca, data=test)
# Verifying Predictions:
predictions#.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
0,-1.710996,0.055250,1.581712,-0.224471,0.953706,0.291418,-0.042769,0.649157,-0.523387,0.979981,0,706.495324
1,-1.556816,1.981025,-1.905968,-1.210341,-1.038838,-0.000825,0.189737,-1.362684,-1.668756,-1.352670,1,1047.519400
2,-1.696922,0.186878,-0.593644,-0.359845,-1.434838,-1.279352,1.268013,0.911062,1.190367,-0.751265,0,815.716003
3,-1.799183,-0.067348,1.737263,-0.212815,-1.454541,-1.372023,1.197457,0.743684,1.195752,-0.875281,0,898.604086
4,0.903328,0.209710,1.835348,-0.039473,0.654920,0.131069,1.525368,0.882318,1.566223,-1.199386,0,813.023609
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.829905,-0.233314,0.478071,-1.265075,1.064893,1.215546,1.436378,0.719061,1.543411,-1.288400,0,817.368536
96,-1.629686,-0.920098,0.672940,-0.126304,0.839491,1.005736,1.035478,0.497486,1.122700,-0.965519,0,735.556402
97,-0.517968,0.452519,0.548592,0.013100,-1.615810,-1.252932,-0.955745,-1.622076,-0.336469,-0.797227,0,733.207104
98,0.760734,0.451004,1.641725,-0.175392,0.491224,1.205472,-0.730244,-1.566600,-0.057038,-1.076261,0,722.421767
99,0.867208,-0.286038,0.100656,1.027060,0.506761,1.190875,-1.111994,-0.906580,-0.996532,0.458125,0,627.706848

In [21]:
# @title Save/Load Model
# Saving  Model:
save_model(pca,  'PyCaretModelPCA')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['Col1', 'Col2', 'Col3', 'Col4',
                                              'Col5', 'Col6', 'Col7', 'Col8',
                                              'Col9', 'Col10'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('trained_model',
                  PCA(contamination=0.05, copy=True, iterated_power='auto', n_components=None,
   n_selected_components=None, random_state=0, standardization=True,
   svd_solver='auto', tol=0.0, weighted=True, whiten=False))]),
 'PyCaretModelPCA.pkl')

In [22]:
# Loading Model:
model=load_model('PyCaretModelPCA')

Transformation Pipeline and Model Successfully Loaded

In [23]:
# New Predictions:
new=predict_model(model, data=test)
# Verifying Results:
new#.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
0,0.052495,0.506366,0.907679,0.438323,0.905472,0.607198,0.497363,0.602278,0.351128,0.703629,0,706.495309
1,0.092108,0.995017,0.014465,0.176371,0.241530,0.514724,0.562208,0.158963,0.073715,0.208463,1,1047.519380
2,0.056111,0.539765,0.350559,0.402354,0.109578,0.110161,0.862937,0.659989,0.766205,0.336127,0,815.716038
3,0.029838,0.475257,0.947517,0.441421,0.103012,0.080837,0.843259,0.623107,0.767509,0.309801,0,898.604050
4,0.724176,0.545559,0.972637,0.487479,0.805912,0.556459,0.934712,0.653656,0.857239,0.241002,0,813.023591
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.705312,0.433145,0.625031,0.161827,0.942521,0.899618,0.909893,0.617682,0.851713,0.222106,0,817.368527
96,0.073386,0.258878,0.674938,0.464407,0.867414,0.833228,0.798083,0.568857,0.749816,0.290646,0,735.556377
97,0.359012,0.607170,0.643091,0.501448,0.049276,0.118521,0.242736,0.101806,0.396400,0.326370,0,733.207091
98,0.687541,0.606785,0.923049,0.451364,0.751367,0.896430,0.305628,0.114030,0.464079,0.267138,0,722.421775
99,0.714896,0.419766,0.528373,0.770864,0.756544,0.891811,0.199159,0.259467,0.236530,0.592851,0,627.706865

In [24]:
# @title Experiment
experiment=AnomalyExperiment()
# Type:
type(experiment)

pycaret.anomaly.oop.AnomalyExperiment

In [25]:
# Experiment SetUp:
experiment.setup(data=train, normalize=True, session_id=0, experiment_name='anomaly')

In [26]:
# Model Creation/Training:
iforest=experiment.create_model('iforest')
iforest

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

IForest(behaviour='new', bootstrap=False, contamination=0.05,
    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,
    random_state=0, verbose=0)

In [27]:
# Model Assignment:
# Assigns Anomaly Labels to Taining Data
anomalies=experiment.assign_model(iforest)
anomalies

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
0,0.263995,0.764929,0.138424,0.935242,0.605867,0.518790,0.912225,0.608234,0.723782,0.733591,0,-0.015787
1,0.546092,0.653975,0.065575,0.227772,0.845269,0.837066,0.272379,0.331679,0.429297,0.367422,0,-0.080828
2,0.336714,0.538842,0.192801,0.553563,0.074515,0.332993,0.365792,0.861309,0.899017,0.088600,1,0.004413
3,0.325261,0.805968,0.957033,0.331665,0.307923,0.355315,0.501899,0.558449,0.885169,0.182754,0,-0.015964
4,0.212465,0.780305,0.458444,0.634509,0.373030,0.465651,0.413997,0.013080,0.570250,0.736672,0,-0.032098
...,...,...,...,...,...,...,...,...,...,...,...,...
895,0.305055,0.656837,0.331665,0.822525,0.907127,0.882276,0.855732,0.584786,0.808640,0.242762,0,-0.085529
896,0.812627,0.864258,0.616604,0.167966,0.811223,0.938071,0.418462,0.472306,0.348347,0.671129,0,-0.078626
897,0.250967,0.138627,0.919703,0.461234,0.886555,0.869888,0.800908,0.530324,0.779433,0.234952,0,-0.067786
898,0.502436,0.936820,0.580062,0.540773,0.151995,0.059452,0.225220,0.242755,0.279385,0.538755,0,-0.075605
899,0.457991,0.017755,0.714113,0.125992,0.063316,0.154739,0.922974,0.692299,0.816777,0.307592,0,-0.028678

In [28]:
# Plot Model
# Model Analysis/Visualyzing Results – tSNE:
plot_model(iforest          ,    plot='tsne')

In [29]:
# Plot Model
# Model Analysis/Visualyzing Results – UMAP:
plot_model(iforest          ,    plot='umap')

In [30]:
# Model Evaluation:
experiment.evaluate_model(iforest)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [31]:
# Test Prediction:
predictions=experiment.predict_model(iforest, data=test)
predictions

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Anomaly,Anomaly_Score
0,-0.887793,1.074247,-1.421955,1.645702,0.054566,0.012025,1.444739,0.676189,1.015213,1.121128,0,-0.015787
1,0.210187,0.636977,-1.706402,-1.016890,0.773034,1.017864,-0.849460,-0.578871,-0.200645,-0.603839,0,-0.080828
2,-0.604757,0.183241,-1.209630,0.209237,-1.540066,-0.575143,-0.514522,1.824688,1.738714,-1.917326,1,0.004413
3,-1.556816,1.981025,-1.905968,-1.210341,-1.038838,-0.000825,0.189737,-1.362684,-1.668756,-1.352670,1,0.055171
4,-0.649334,1.235982,1.774422,-0.625885,-0.839587,-0.504600,-0.026506,0.450256,1.681542,-1.473780,0,-0.015964
...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.727980,0.648259,-0.667418,1.221488,0.958674,1.160740,1.242179,0.569774,1.365572,-1.191093,0,-0.085529
996,1.247596,1.465704,0.445166,-1.241973,0.670859,1.337067,-0.325673,0.059323,-0.534867,0.826879,0,-0.078626
997,-0.938502,-1.394009,1.628662,-0.138245,0.896935,1.121590,1.045608,0.322618,1.244981,-1.227886,0,-0.067786
998,0.040266,1.751670,0.302483,0.161102,-1.307540,-1.439605,-1.018549,-0.982420,-0.819596,0.203285,0,-0.075605
999,-0.132723,-1.870366,0.825906,-1.399942,-1.573675,-1.138474,1.483280,1.057689,1.399165,-0.885690,0,-0.028678

In [32]:
# @title Save/Load Experiment
# Save Experiment:
save_experiment(           'ExperimentPipeLine')
# Load Experiment:
experiment=load_experiment('ExperimentPipeLine', data=data)